--Desafio: calculando a idade do cliente

CREATE TRIGGER TG_CLIENTES_IDADE
ON CLIENTES
AFTER INSERT, UPDATE, DELETE 
AS 
BEGIN
UPDATE CLIENTES SET IDADE = 
    DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE());
END;

INSERT INTO CLIENTES
(CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO,
CEP, DATA_NASCIMENTO, GENERO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA)
VALUES
('38472385792', 'Fulano', 'Rua X', 'Bairro Y', 'São Paulo', 'SP',
'9485256', '2000-01-01', 'M', '40.0', '20.0', 0);

SELECT DATA_NASCIMENTO, IDADE FROM CLIENTES WHERE CPF = '38472385792';